### ISSUE TITLE
Restarting HomeBridge - Cannot add Bridged accessory error

### ISSUE THREAD

**Issue by Gordon-Newell** [chriscn/homebridge-mihome4u#7]
**Describe the bug**
When restarting homebridge with devices configured and error occurs in the logs which caused homebridge to SIGTERM

**To Reproduce**
1. Multiple MiHome Switches configured
2. Restart Home Bridge
3. 2nd Restart causes error

**Expected behavior**
No errors in the log

**Versions:**
 - Homebridge v1.1.0
 - Node JS v12.16.3
 - NPM v6.14.4

**Work Around**
- Remove MiHome4u from config and restart
- Add back to the config restart
- Reconfigure devices, all automations and scenes

**Error on 2nd reboot after adding config** 
[5/24/2020, 09:47:36] [MiHome] Registering new accessory with name Bedroom Light with id 250489
HAP Warning: Characteristic 00000014-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000049-0000-1000-8000-0026BB765291. Adding anyway.
[5/24/2020, 09:47:36] [MiHome] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: b95ee355-f3cc-489f-8c14-35d4f6fb3e6b
    at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:414:15)
    at Bridge.Accessory._this.addBridgedAccessories (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:448:12)
    at Server.handleRegisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:527:17)
    at HomebridgeAPI.emit (events.js:310:20)
    at HomebridgeAPI.registerPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/api.ts:316:10)
    at /usr/local/lib/node_modules/homebridge-mihome4u/src/platform.ts:129:26
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Log Extract SIGTERM**
[5/24/2020, 09:25:39] [MiHome] Unknown device found in cache with type undefined
[5/24/2020, 09:25:39] [MiHome] Unknown device found in cache with type undefined
[5/24/2020, 09:25:39] [MiHome] Unknown device found in cache with type undefined
[5/24/2020, 09:25:39] [MiHome] Unknown device found in cache with type undefined
[5/24/2020, 09:25:39] [MiHome] Unknown device found in cache with type undefined
[5/24/2020, 09:25:39] [MiHome] Unknown device found in cache with type undefined
[5/24/2020, 09:25:39] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: b95ee355-f3cc-489f-8c14-35d4f6fb3e6b
    at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:414:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:309:19
    at Array.filter (<anonymous>)
    at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:269:69)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:157:10)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

**Comment by chriscn** [comment]
Can you `rm` the cached accessories? The bridged Accessory sounds like a Homebridge issue.

**Comment by Gordon-Newell** [comment]
I tried that, restarted and got 

[5/25/2020, 08:32:49] [MiHome] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: b95ee355-f3cc-489f-8c14-35d4f6fb3e6b
    at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:414:15)
    at Bridge.Accessory._this.addBridgedAccessories (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:448:12)
    at Server.handleRegisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:527:17)
    at HomebridgeAPI.emit (events.js:310:20)
    at HomebridgeAPI.registerPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/api.ts:316:10)
    at /usr/local/lib/node_modules/homebridge-mihome4u/src/platform.ts:129:26
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

I have other cached accessories from other plug-ins that are not seeing this error these are homebridge-zp and homebridge-upnp accessories

**Comment by Gordon-Newell** [comment]
This error is continuing and after updating and restarting homebridge, the plugin is causing the service to crash.

Everytime my only option is to remove the config for the plugin

**Comment by Gordon-Newell** [comment]
Hi Chris I have a solution, I do not have permissions to submit a branch, if you can grant me permissions I can submit a pull request

**Comment by Gordon-Newell** [comment]
`configureAccessory(accessory: PlatformAccessory) {
    switch (accessory.context.device.device_type.toLowerCase()) {
      case 'light':
      case 'control':
        this.log.info(`Restoring accessory from cache:"${accessory.displayName}" of type "${accessory.context.device.device_type}"`);
        new MiHomePlug(this, accessory);
        this.accessories.push(accessory);
        break;
      default:
        this.log.info(`Unknown cached accessory type "${accessory.context.device.device_type}" for device "${accessory.displayName}"`);
    }
  }
`

**Comment by Gordon-Newell** [comment]
configureAccessory(accessory: PlatformAccessory) {
    switch (accessory.context.device.device_type.toLowerCase()) {
      case 'light':
      case 'control':
        this.log.info(`Restoring accessory from cache:"${accessory.displayName}" of type "${accessory.context.device.device_type}"`);
        new MiHomePlug(this, accessory);
        this.accessories.push(accessory);
        break;
      default:
        this.log.info(`Unknown cached accessory type "${accessory.context.device.device_type}" for device "${accessory.displayName}"`);
    }
  }
